name: qq_badge
description: A new Flutter project.
version: 0.0.2
homepage: https://github.com/hrxiang/QqBadge.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter